/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as AppTargetAccountsRouteImport } from './routes/app.target-accounts'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppHotLeadsRouteImport } from './routes/app.hot-leads'
import { Route as AppConsentAuditRouteImport } from './routes/app.consent-audit'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as MarketingSignupRouteImport } from './routes/_marketing.signup'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingLoginRouteImport } from './routes/_marketing.login'
import { Route as MarketingGdprRouteImport } from './routes/_marketing.gdpr'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing.features'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/app.companies.$companyId'
import { Route as ApiPublicTDotjsRouteImport } from './routes/api.public.t[.]js'
import { Route as ApiPublicIdentifyRouteImport } from './routes/api.public.identify'
import { Route as ApiPublicEraseRouteImport } from './routes/api.public.erase'
import { Route as ApiPublicCollectRouteImport } from './routes/api.public.collect'
import { Route as MarketingDocsInstallRouteImport } from './routes/_marketing.docs.install'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AppTargetAccountsRoute = AppTargetAccountsRouteImport.update({
  id: '/target-accounts',
  path: '/target-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppHotLeadsRoute = AppHotLeadsRouteImport.update({
  id: '/hot-leads',
  path: '/hot-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentAuditRoute = AppConsentAuditRouteImport.update({
  id: '/consent-audit',
  path: '/consent-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const MarketingSignupRoute = MarketingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingGdprRoute = MarketingGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const ApiPublicTDotjsRoute = ApiPublicTDotjsRouteImport.update({
  id: '/api/public/t.js',
  path: '/api/public/t.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIdentifyRoute = ApiPublicIdentifyRouteImport.update({
  id: '/api/public/identify',
  path: '/api/public/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEraseRoute = ApiPublicEraseRouteImport.update({
  id: '/api/public/erase',
  path: '/api/public/erase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingDocsInstallRoute = MarketingDocsInstallRouteImport.update({
  id: '/docs/install',
  path: '/docs/install',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof MarketingFeaturesRoute
  '/gdpr': typeof MarketingGdprRoute
  '/login': typeof MarketingLoginRoute
  '/pricing': typeof MarketingPricingRoute
  '/signup': typeof MarketingSignupRoute
  '/app/companies': typeof AppCompaniesRouteWithChildren
  '/app/consent-audit': typeof AppConsentAuditRoute
  '/app/hot-leads': typeof AppHotLeadsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/target-accounts': typeof AppTargetAccountsRoute
  '/app/': typeof AppIndexRoute
  '/docs/install': typeof MarketingDocsInstallRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/erase': typeof ApiPublicEraseRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/t.js': typeof ApiPublicTDotjsRoute
  '/app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/features': typeof MarketingFeaturesRoute
  '/gdpr': typeof MarketingGdprRoute
  '/login': typeof MarketingLoginRoute
  '/pricing': typeof MarketingPricingRoute
  '/signup': typeof MarketingSignupRoute
  '/app/companies': typeof AppCompaniesRouteWithChildren
  '/app/consent-audit': typeof AppConsentAuditRoute
  '/app/hot-leads': typeof AppHotLeadsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/target-accounts': typeof AppTargetAccountsRoute
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/docs/install': typeof MarketingDocsInstallRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/erase': typeof ApiPublicEraseRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/t.js': typeof ApiPublicTDotjsRoute
  '/app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/gdpr': typeof MarketingGdprRoute
  '/_marketing/login': typeof MarketingLoginRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/signup': typeof MarketingSignupRoute
  '/app/companies': typeof AppCompaniesRouteWithChildren
  '/app/consent-audit': typeof AppConsentAuditRoute
  '/app/hot-leads': typeof AppHotLeadsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/target-accounts': typeof AppTargetAccountsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/_marketing/docs/install': typeof MarketingDocsInstallRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/api/public/erase': typeof ApiPublicEraseRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/t.js': typeof ApiPublicTDotjsRoute
  '/app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/features'
    | '/gdpr'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/companies'
    | '/app/consent-audit'
    | '/app/hot-leads'
    | '/app/integrations'
    | '/app/people'
    | '/app/settings'
    | '/app/target-accounts'
    | '/app/'
    | '/docs/install'
    | '/api/public/collect'
    | '/api/public/erase'
    | '/api/public/identify'
    | '/api/public/t.js'
    | '/app/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/features'
    | '/gdpr'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/companies'
    | '/app/consent-audit'
    | '/app/hot-leads'
    | '/app/integrations'
    | '/app/people'
    | '/app/settings'
    | '/app/target-accounts'
    | '/'
    | '/app'
    | '/docs/install'
    | '/api/public/collect'
    | '/api/public/erase'
    | '/api/public/identify'
    | '/api/public/t.js'
    | '/app/companies/$companyId'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/_marketing/features'
    | '/_marketing/gdpr'
    | '/_marketing/login'
    | '/_marketing/pricing'
    | '/_marketing/signup'
    | '/app/companies'
    | '/app/consent-audit'
    | '/app/hot-leads'
    | '/app/integrations'
    | '/app/people'
    | '/app/settings'
    | '/app/target-accounts'
    | '/_marketing/'
    | '/app/'
    | '/_marketing/docs/install'
    | '/api/public/collect'
    | '/api/public/erase'
    | '/api/public/identify'
    | '/api/public/t.js'
    | '/app/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
  ApiPublicEraseRoute: typeof ApiPublicEraseRoute
  ApiPublicIdentifyRoute: typeof ApiPublicIdentifyRoute
  ApiPublicTDotjsRoute: typeof ApiPublicTDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/target-accounts': {
      id: '/app/target-accounts'
      path: '/target-accounts'
      fullPath: '/app/target-accounts'
      preLoaderRoute: typeof AppTargetAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hot-leads': {
      id: '/app/hot-leads'
      path: '/hot-leads'
      fullPath: '/app/hot-leads'
      preLoaderRoute: typeof AppHotLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consent-audit': {
      id: '/app/consent-audit'
      path: '/consent-audit'
      fullPath: '/app/consent-audit'
      preLoaderRoute: typeof AppConsentAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/signup': {
      id: '/_marketing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MarketingSignupRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/gdpr': {
      id: '/_marketing/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof MarketingGdprRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/companies/$companyId': {
      id: '/app/companies/$companyId'
      path: '/$companyId'
      fullPath: '/app/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/api/public/t.js': {
      id: '/api/public/t.js'
      path: '/api/public/t.js'
      fullPath: '/api/public/t.js'
      preLoaderRoute: typeof ApiPublicTDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/identify': {
      id: '/api/public/identify'
      path: '/api/public/identify'
      fullPath: '/api/public/identify'
      preLoaderRoute: typeof ApiPublicIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erase': {
      id: '/api/public/erase'
      path: '/api/public/erase'
      fullPath: '/api/public/erase'
      preLoaderRoute: typeof ApiPublicEraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/docs/install': {
      id: '/_marketing/docs/install'
      path: '/docs/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof MarketingDocsInstallRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingGdprRoute: typeof MarketingGdprRoute
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingSignupRoute: typeof MarketingSignupRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingDocsInstallRoute: typeof MarketingDocsInstallRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingGdprRoute: MarketingGdprRoute,
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingSignupRoute: MarketingSignupRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingDocsInstallRoute: MarketingDocsInstallRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppCompaniesRouteChildren {
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppConsentAuditRoute: typeof AppConsentAuditRoute
  AppHotLeadsRoute: typeof AppHotLeadsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTargetAccountsRoute: typeof AppTargetAccountsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppConsentAuditRoute: AppConsentAuditRoute,
  AppHotLeadsRoute: AppHotLeadsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTargetAccountsRoute: AppTargetAccountsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
  ApiPublicEraseRoute: ApiPublicEraseRoute,
  ApiPublicIdentifyRoute: ApiPublicIdentifyRoute,
  ApiPublicTDotjsRoute: ApiPublicTDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
